from __future__ import annotations

from sqlalchemy.orm import Session

from app.models.source import Source
from app.repositories.source_repository import SourceRepository

DEFAULT_SOURCES: list[dict] = [
    # tier-1 (quality_score 0.9)
    {
        "name": "BBC News",
        "kind": "rss",
        "url": "http://feeds.bbci.co.uk/news/rss.xml",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.9,
        "tier": "tier-1",
    },
    {
        "name": "Reuters World News",
        "kind": "rss",
        "url": "https://www.reutersagency.com/feed/",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.9,
        "tier": "tier-1",
    },
    {
        "name": "The Guardian International",
        "kind": "rss",
        "url": "https://www.theguardian.com/international/rss",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.9,
        "tier": "tier-1",
    },
    {
        "name": "NYT Home Page",
        "kind": "rss",
        "url": "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.9,
        "tier": "tier-1",
    },
    {
        "name": "AP News",
        "kind": "rss",
        "url": "https://apnews.com/rss",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.9,
        "tier": "tier-1",
    },
    {
        "name": "NPR News",
        "kind": "rss",
        "url": "https://feeds.npr.org/1001/rss.xml",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.9,
        "tier": "tier-1",
    },
    {
        "name": "Washington Post",
        "kind": "rss",
        "url": "https://feeds.washingtonpost.com/rss/world",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.9,
        "tier": "tier-1",
    },
    {
        "name": "Al Jazeera English",
        "kind": "rss",
        "url": "https://www.aljazeera.com/xml/rss/all.xml",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.9,
        "tier": "tier-1",
    },
    {
        "name": "DW (Deutsche Welle)",
        "kind": "rss",
        "url": "https://rss.dw.com/rdf/rss-en-all",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.9,
        "tier": "tier-1",
    },
    {
        "name": "France 24 English",
        "kind": "rss",
        "url": "https://www.france24.com/en/rss",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.9,
        "tier": "tier-1",
    },
    # tier-2 (quality_score 0.7) — general news
    {
        "name": "CNN Edition",
        "kind": "rss",
        "url": "http://rss.cnn.com/rss/edition.rss",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.7,
        "tier": "tier-2",
    },
    {
        "name": "ABC News",
        "kind": "rss",
        "url": "https://abcnews.go.com/abcnews/topstories",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.7,
        "tier": "tier-2",
    },
    {
        "name": "NBC News",
        "kind": "rss",
        "url": "https://feeds.nbcnews.com/nbcnews/public/news",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.7,
        "tier": "tier-2",
    },
    {
        "name": "CBS News",
        "kind": "rss",
        "url": "https://www.cbsnews.com/latest/rss/main",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.7,
        "tier": "tier-2",
    },
    {
        "name": "Sky News",
        "kind": "rss",
        "url": "https://feeds.skynews.com/feeds/rss/home.xml",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.7,
        "tier": "tier-2",
    },
    {
        "name": "USA Today",
        "kind": "rss",
        "url": "https://rssfeeds.usatoday.com/usatoday-newstopstories",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.7,
        "tier": "tier-2",
    },
    {
        "name": "The Independent",
        "kind": "rss",
        "url": "https://www.independent.co.uk/news/world/rss",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.7,
        "tier": "tier-2",
    },
    {
        "name": "Politico",
        "kind": "rss",
        "url": "https://rss.politico.com/politics.xml",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.7,
        "tier": "tier-2",
    },
    {
        "name": "The Hill",
        "kind": "rss",
        "url": "https://thehill.com/feed",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.7,
        "tier": "tier-2",
    },
    # tier-2 (quality_score 0.7) — tech & business
    {
        "name": "Ars Technica",
        "kind": "rss",
        "url": "http://feeds.arstechnica.com/arstechnica/index/",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.7,
        "tier": "tier-2",
    },
    {
        "name": "The Verge",
        "kind": "rss",
        "url": "https://www.theverge.com/rss/index.xml",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.7,
        "tier": "tier-2",
    },
    {
        "name": "WIRED",
        "kind": "rss",
        "url": "https://www.wired.com/feed/rss",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.7,
        "tier": "tier-2",
    },
    {
        "name": "TechCrunch",
        "kind": "rss",
        "url": "https://techcrunch.com/feed/",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.7,
        "tier": "tier-2",
    },
    {
        "name": "CNBC",
        "kind": "rss",
        "url": "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.7,
        "tier": "tier-2",
    },
    {
        "name": "MarketWatch",
        "kind": "rss",
        "url": "https://www.marketwatch.com/rss/topstories",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.7,
        "tier": "tier-2",
    },
    # tier-2 (quality_score 0.8) — science
    {
        "name": "New Scientist",
        "kind": "rss",
        "url": "https://www.newscientist.com/feed/home",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.8,
        "tier": "tier-2",
    },
    {
        "name": "Scientific American",
        "kind": "rss",
        "url": "https://www.scientificamerican.com/feed/",
        "language": "en",
        "enabled": True,
        "fetch_interval_minutes": 30,
        "quality_score": 0.8,
        "tier": "tier-2",
    },
]


class SourceService:

    def __init__(self, repository: SourceRepository):
        self.repository = repository

    def get_default_sources(self) -> list[dict]:
        return list(DEFAULT_SOURCES)

    def seed_default_sources(self, db: Session) -> list[Source]:
        existing_names = {s.name for s in self.repository.list_all()}
        for data in DEFAULT_SOURCES:
            if data["name"] not in existing_names:
                self.repository.create(**data)
        return self.repository.list_all()

    def get_active_fetchable_sources(self) -> list[Source]:
        return self.repository.get_active_fetchable_sources()
