#!/usr/bin/env python3
"""Sync OpenAPI schema to TypeScript type definitions.

Reads ``packages/shared-types/openapi.json`` and generates one TypeScript
interface per resource schema into ``packages/shared-types/src/generated/``.

Usage:
    python scripts/sync-shared-types.py
"""

from __future__ import annotations

import json
import os
import re
from typing import Any

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.dirname(_SCRIPT_DIR)
_OPENAPI_PATH = os.path.join(
    _REPO_ROOT, "packages", "shared-types", "openapi.json"
)
_OUTPUT_DIR = os.path.join(
    _REPO_ROOT, "packages", "shared-types", "src", "generated"
)

# Resource schemas we want to export.  Anything else in components.schemas
# (e.g. validation helpers) is silently skipped.
_PUBLIC_RESOURCES: set[str] = {
    "HealthResource",
    "ApiError",
    "DigestResource",
    "DigestEntryResource",
    "ArchiveDateListResource",
    "ClusterDetailResource",
    "ArticleDetailResource",
}


# ---------------------------------------------------------------------------
# JSON-Schema -> TypeScript type-string
# ---------------------------------------------------------------------------

def _json_schema_to_ts(
    prop: dict[str, Any],
    schemas: dict[str, Any],
) -> str:
    """Convert a single JSON-Schema property to a TypeScript type string."""
    # $ref reference
    if "$ref" in prop:
        ref_name = prop["$ref"].rsplit("/", 1)[-1]
        return ref_name

    # Enum / Literal
    if "enum" in prop:
        return " | ".join(json.dumps(v) for v in prop["enum"])

    # anyOf → union
    if "anyOf" in prop:
        parts = [_json_schema_to_ts(p, schemas) for p in prop["anyOf"]]
        return " | ".join(parts)

    # allOf → intersection (unlikely for our schemas but handled for safety)
    if "allOf" in prop:
        parts = [_json_schema_to_ts(p, schemas) for p in prop["allOf"]]
        return " & ".join(parts)

    json_type = prop.get("type")

    if json_type == "string":
        return "string"
    if json_type in ("integer", "number"):
        return "number"
    if json_type == "boolean":
        return "boolean"
    if json_type == "null":
        return "null"
    if json_type == "array":
        items = prop.get("items", {})
        inner = _json_schema_to_ts(items, schemas)
        return f"{inner}[]"
    if json_type == "object" or "properties" in prop:
        # inline object
        props = prop.get("properties", {})
        required = set(prop.get("required", []))
        lines: list[str] = []
        for name, sub in props.items():
            opt = "" if name in required else "?"
            ts_type = _json_schema_to_ts(sub, schemas)
            lines.append(f"  {name}{opt}: {ts_type};")
        return "{\n" + "\n".join(lines) + "\n}"

    # Fallback
    return "unknown"


def _schema_to_interface(
    name: str,
    schema: dict[str, Any],
    all_schemas: dict[str, Any],
) -> str:
    """Generate a TypeScript interface string for a resource schema."""
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))

    lines: list[str] = [f"export interface {name} {{"]
    for prop_name, prop_schema in properties.items():
        opt = "" if prop_name in required else "?"
        ts_type = _json_schema_to_ts(prop_schema, all_schemas)
        lines.append(f"  {prop_name}{opt}: {ts_type};")
    lines.append("}")
    return "\n".join(lines)


def _to_pascal_case(name: str) -> str:
    """Convert a schema name (PascalCase) to a filename stem (kebab-case)."""
    # Insert hyphens before capitals
    s1 = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", name)
    result = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", s1).lower()
    return result


def sync_shared_types(
    openapi_path: str | None = None,
    output_dir: str | None = None,
) -> list[str]:
    """Read the OpenAPI schema and write TypeScript interfaces.

    Returns the list of files written (absolute paths).
    """
    src = openapi_path or _OPENAPI_PATH
    dest_dir = output_dir or _OUTPUT_DIR

    with open(src, encoding="utf-8") as fh:
        schema = json.load(fh)

    components = schema.get("components", {}).get("schemas", {})
    os.makedirs(dest_dir, exist_ok=True)

    written: list[str] = []
    index_exports: list[str] = []

    for name, comp_schema in components.items():
        if name not in _PUBLIC_RESOURCES:
            continue

        ts_code = _schema_to_interface(name, comp_schema, components)
        filename = _to_pascal_case(name) + ".ts"
        filepath = os.path.join(dest_dir, filename)

        with open(filepath, "w", encoding="utf-8") as fh:
            fh.write("// Auto-generated by scripts/sync-shared-types.py\n")
            fh.write("// Do not edit manually.\n\n")
            fh.write(ts_code)
            fh.write("\n")

        written.append(os.path.abspath(filepath))
        # index.ts re-export
        stem = _to_pascal_case(name)
        index_exports.append(
            f'export type {{ {name} }} from "./{stem}.js";'
        )

    # Write barrel index
    index_path = os.path.join(dest_dir, "index.ts")
    with open(index_path, "w", encoding="utf-8") as fh:
        fh.write("// Auto-generated by scripts/sync-shared-types.py\n")
        fh.write("// Do not edit manually.\n\n")
        for line in index_exports:
            fh.write(line + "\n")
    written.append(os.path.abspath(index_path))

    return written


# ---------------------------------------------------------------------------
# CLI entry-point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    files = sync_shared_types()
    print(f"Generated {len(files)} file(s):")
    for f in files:
        print(f"  {f}")
